{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6bde7f5e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[]\n"
     ]
    }
   ],
   "source": [
    "import pytesseract\n",
    "from pdf2image import convert_from_path\n",
    "import cv2, json\n",
    "from pytesseract import Output\n",
    "import numpy as np\n",
    "\n",
    "pdf_path = \"/home/name-1/AI-Agent/new-born/data/Kedir Jara CBE Statement.pdf\"\n",
    "\n",
    "# Convert PDF to images (one per page)\n",
    "pages = convert_from_path(pdf_path, dpi=300)\n",
    "\n",
    "transactions = []\n",
    "\n",
    "for page_num, page in enumerate(pages, start=1):\n",
    "    # Convert to OpenCV format\n",
    "    img = cv2.cvtColor(np.array(page), cv2.COLOR_RGB2BGR)\n",
    "    \n",
    "    # Preprocess\n",
    "    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
    "    gray = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]\n",
    "    \n",
    "    # OCR\n",
    "    custom_config = r'--oem 3 --psm 6'\n",
    "    data = pytesseract.image_to_data(gray, config=custom_config, output_type=Output.DICT)\n",
    "\n",
    "    # Collect rows\n",
    "    rows, current_row, last_y = [], [], None\n",
    "    for i, text in enumerate(data[\"text\"]):\n",
    "        if text.strip() == \"\":\n",
    "            continue\n",
    "        y = data[\"top\"][i]\n",
    "        if last_y is None or abs(y - last_y) < 15:\n",
    "            current_row.append(text)\n",
    "        else:\n",
    "            rows.append(current_row)\n",
    "            current_row = [text]\n",
    "        last_y = y\n",
    "    if current_row:\n",
    "        rows.append(current_row)\n",
    "\n",
    "    # Parse into JSON\n",
    "    for row in rows:\n",
    "        if len(row) >= 6 and row[0].count(\"/\") == 2:\n",
    "            try:\n",
    "                posting_date = row[0]\n",
    "                value_date = row[1]\n",
    "                description = \" \".join(row[2:-3])\n",
    "                debit_amount = row[-3] if row[-3] != \"0.00\" else None\n",
    "                credit_amount = row[-2] if row[-2] != \"0.00\" else None\n",
    "                balance = row[-1]\n",
    "\n",
    "                transactions.append({\n",
    "                    \"page\": page_num,\n",
    "                    \"posting_date\": posting_date,\n",
    "                    \"value_date\": value_date,\n",
    "                    \"description\": description,\n",
    "                    \"debit_amount\": debit_amount,\n",
    "                    \"credit_amount\": credit_amount,\n",
    "                    \"balance\": balance\n",
    "                })\n",
    "            except:\n",
    "                continue\n",
    "\n",
    "# Save JSON\n",
    "with open(\"transactions.json\", \"w\") as f:\n",
    "    json.dump(transactions, f, indent=4)\n",
    "\n",
    "print(json.dumps(transactions[:5], indent=4))  # preview first 5\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "eb4a8bde",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "'\n",
      "COMMERCIAL BANK OF ETHIOPIA\n",
      "NESSIHA BRANCH\n",
      "Pe ee ee\n",
      "Account Statement |\n",
      "1049421269 ' ys\n",
      "KEDIR JARA TOBI Om\n",
      "ORWA : A>\n",
      "ESD |\n",
      "SHASHEMENE x) = |\n",
      "ee JESS |\n",
      "Statement of Transactions For the period From 01 AUG 2024 to 02 JAN 2025 Js ey, |\n",
      ": fe :\n",
      "Account :1000374906899 KEDIR JARA J OBI\n",
      "Currency :ETB\n",
      "ie Account Type :Amana Current Account er\n",
      "ova fee aonevew | FTaaanczei [reqadone vam] acezo | omad asa)\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from pdf2image import convert_from_path\n",
    "import pytesseract\n",
    "import numpy as np\n",
    "import cv2\n",
    "\n",
    "def extract_ocr_text(pdf_path):\n",
    "    pages = convert_from_path(pdf_path, dpi=300)\n",
    "    texts = []\n",
    "    for page_num, page in enumerate(pages, start=1):\n",
    "        img = cv2.cvtColor(np.array(page), cv2.COLOR_RGB2BGR)\n",
    "        text = pytesseract.image_to_string(img, config=\"--psm 6\")\n",
    "        texts.append({\"page\": page_num, \"text\": text})\n",
    "    return texts\n",
    "\n",
    "ocr_output = extract_ocr_text(\"/home/name-1/AI-Agent/new-born/data/Kedir Jara CBE Statement.pdf\")\n",
    "print(ocr_output[0][\"text\"][:500])  # preview first page text\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3e8cb02e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Page 1 failed JSON parsing\n",
      "Page 2 failed JSON parsing\n",
      "Page 3 failed JSON parsing\n",
      "Page 4 failed JSON parsing\n",
      "Page 5 failed JSON parsing\n",
      "Page 6 failed JSON parsing\n",
      "Page 7 failed JSON parsing\n",
      "Page 8 failed JSON parsing\n",
      "Page 9 failed JSON parsing\n",
      "Page 10 failed JSON parsing\n",
      "Page 11 failed JSON parsing\n",
      "Page 12 failed JSON parsing\n",
      "Page 13 failed JSON parsing\n",
      "Page 14 failed JSON parsing\n",
      "Page 15 failed JSON parsing\n",
      "[]\n"
     ]
    }
   ],
   "source": [
    "from langchain_groq import ChatGroq\n",
    "from langchain.prompts import ChatPromptTemplate\n",
    "import json\n",
    "from dotenv import load_dotenv\n",
    "import os\n",
    "load_dotenv()\n",
    "# Groq LLM instance\n",
    "llm = ChatGroq(\n",
    "    model=\"llama3-70b-8192\",  # example\n",
    "    temperature=0\n",
    ")\n",
    "\n",
    "# Define prompt template for structured parsing\n",
    "prompt = ChatPromptTemplate.from_template(\"\"\"\n",
    "You are a financial data extractor.\n",
    "From the following bank statement text, extract transactions into JSON objects\n",
    "with fields:\n",
    "- posting_date\n",
    "- value_date\n",
    "- description\n",
    "- debit_amount\n",
    "- credit_amount\n",
    "- balance\n",
    "\n",
    "Return ONLY valid JSON list.\n",
    "\n",
    "Text:\n",
    "{text}\n",
    "\"\"\")\n",
    "\n",
    "def extract_transactions_with_llm(ocr_output):\n",
    "    all_transactions = []\n",
    "    for page in ocr_output:\n",
    "        chain = prompt | llm\n",
    "        response = chain.invoke({\"text\": page[\"text\"]})\n",
    "        try:\n",
    "            transactions = json.loads(response.content)\n",
    "            for t in transactions:\n",
    "                t[\"page\"] = page[\"page\"]\n",
    "            all_transactions.extend(transactions)\n",
    "        except Exception:\n",
    "            print(f\"Page {page['page']} failed JSON parsing\")\n",
    "    return all_transactions\n",
    "\n",
    "transactions = extract_transactions_with_llm(ocr_output)\n",
    "\n",
    "# Save to file\n",
    "with open(\"transactions.json\", \"w\") as f:\n",
    "    json.dump(transactions, f, indent=4)\n",
    "\n",
    "print(json.dumps(transactions[:5], indent=4))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7db54013",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import json\n",
    "import cv2\n",
    "import pytesseract\n",
    "import numpy as np\n",
    "from pdf2image import convert_from_path\n",
    "from langchain_groq import ChatGroq\n",
    "from langchain.prompts import ChatPromptTemplate\n",
    "\n",
    "# =============== CONFIG =================\n",
    "PDF_PATH = \"/home/name-1/AI-Agent/new-born/data/bank-statement/OTHER STAT HABESHA (2)(1).pdf\"\n",
    "OUTPUT_JSON = \"transactions_habesha.json\"\n",
    "\n",
    "# Set tesseract path if needed (Linux usually not needed)\n",
    "# pytesseract.pytesseract.tesseract_cmd = r\"/usr/bin/tesseract\"\n",
    "\n",
    "# Groq LLM\n",
    "llm = ChatGroq(\n",
    "    model=\"llama3-70b-8192\",   # Or llama-3.1-70b if available\n",
    "    temperature=0\n",
    ")\n",
    "\n",
    "# Prompt Template for Transaction Extraction\n",
    "prompt = ChatPromptTemplate.from_template(\"\"\"\n",
    "You are a financial data parser.\n",
    "Extract ALL bank transactions from the following raw statement text into JSON.\n",
    "\n",
    "Each transaction must have:\n",
    "- posting_date (MM/DD/YYYY)\n",
    "- value_date (MM/DD/YYYY)\n",
    "- description (string, join multi-line parts into one)\n",
    "- debit_amount (float or null)\n",
    "- credit_amount (float or null)\n",
    "- balance (float)\n",
    "\n",
    "Ignore headers like 'Branch Code', 'Account Number', 'Statement Period', 'Page X of Y'.\n",
    "Return ONLY a JSON list, nothing else.\n",
    "\n",
    "Statement Text:\n",
    "{text}\n",
    "\"\"\")\n",
    "\n",
    "# =============== OCR EXTRACTION =================\n",
    "def extract_ocr_text(pdf_path):\n",
    "    \"\"\"Convert PDF pages to images and OCR each one.\"\"\"\n",
    "    pages = convert_from_path(pdf_path, dpi=300)\n",
    "    texts = []\n",
    "    for page_num, page in enumerate(pages, start=1):\n",
    "        img = cv2.cvtColor(np.array(page), cv2.COLOR_RGB2BGR)\n",
    "        text = pytesseract.image_to_string(img, config=\"--psm 6\")\n",
    "        texts.append({\"page\": page_num, \"text\": text})\n",
    "    return texts\n",
    "\n",
    "# =============== LLM PARSING =================\n",
    "def parse_statement_with_llm(page_text, page_num):\n",
    "    \"\"\"Send OCR text to Groq LLM and return parsed transactions.\"\"\"\n",
    "    chain = prompt | llm\n",
    "    response = chain.invoke({\"text\": page_text})\n",
    "    try:\n",
    "        data = json.loads(response.content)\n",
    "        for t in data:\n",
    "            t[\"page\"] = page_num  # keep track of which page it came from\n",
    "        return data\n",
    "    except Exception as e:\n",
    "        print(f\"⚠️ Page {page_num} failed JSON parsing: {e}\")\n",
    "        print(\"Raw LLM output:\\n\", response.content[:500])\n",
    "        return []\n",
    "\n",
    "# =============== MAIN PIPELINE =================\n",
    "def process_pdf(pdf_path, output_json):\n",
    "    ocr_pages = extract_ocr_text(pdf_path)\n",
    "    all_transactions = []\n",
    "    \n",
    "    for page in ocr_pages:\n",
    "        transactions = parse_statement_with_llm(page[\"text\"], page[\"page\"])\n",
    "        all_transactions.extend(transactions)\n",
    "\n",
    "    # Save to file\n",
    "    with open(output_json, \"w\") as f:\n",
    "        json.dump(all_transactions, f, indent=4)\n",
    "\n",
    "    print(f\"✅ Extracted {len(all_transactions)} transactions\")\n",
    "    print(json.dumps(all_transactions[:5], indent=4))  # preview first 5\n",
    "\n",
    "\n",
    "# Run pipeline\n",
    "if __name__ == \"__main__\":\n",
    "    process_pdf(PDF_PATH, OUTPUT_JSON)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "nat_id",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
